### ISSUE TITLE
TypeError: nunjucks is not a function

### ISSUE THREAD

**Issue by x80486** [Jax-p/vite-plugin-nunjucks#8]
I'm trying to configure `vite-plugin-nunjucks` in a brand new core Web project. The Vite configuration is rather simple:

```typescript
import * as path from "path";
import { defineConfig } from "vite";
import nunjucks from "vite-plugin-nunjucks";

export default defineConfig({
  build: {
    manifest: true,
    outDir: path.resolve(process.cwd(), "dist")
  },
  plugins: [
    nunjucks(),
  ],
  root: path.resolve(process.cwd(), "src")
});
```

The content for `index.html` is:

```html
{% extends "src/_layout.njk" %}

{% set title = "Home" %}

{% block header %}
{% include "src/_header.njk" %}
{%- endblock %}

{% block main %}
<main>
  <h1>Lorem ipsum dolor sit amet.</h1>
  <p>
    Hic voluptatem laboriosam id consequuntur cumque vel ipsum quos. Sed mollitia vitae et similique praesentium non
    omnis harum. Non optio aliquid hic amet assumenda et ducimus nihil et harum nihil aut voluptatem iusto aut doloribus
    tenetur! Vel porro nihil ut pariatur esse ut magni voluptatibus ut modi laboriosam.
  </p>
  <p><span id="jquery-loading">Loading jQuery...</span></p>
</main>
{%- endblock %}

{% block footer %}
{% include "src/_footer.njk" %}
{%- endblock %}
```

...and the content for `_layout.njk` is:

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="IE=edge" http-equiv="x-ua-compatible">

    <title>{{ title }}</title>

    {% block styles %}
    <link href="/styles/global.css" rel="stylesheet" />
    {%- endblock %}

    <link href="/favicon.svg" rel="icon" type="image/svg+xml" />
  </head>
  <body>
    {% block body %}
    <div>
      {% block header %}
      {%- endblock %}

      {% block main %}
      {%- endblock %}

      {% block footer %}
      {%- endblock %}
    </div>
    {%- endblock %}

    {% block extra %}
    {%- endblock %}

    {% block scripts %}
    <script src="/scripts/global.js" type="module"></script>
    {%- endblock %}
  </body>
</html>
```

I'm currently getting the following error(s) for this setup:

```shell
$ npm run build 

> webapp@0.1.1 build
> vite build

failed to load config from /home/x80486/webapp/vite.config.ts
error during build:
TypeError: nunjucks is not a function
    at file:///home/x80486/webapp/vite.config.ts.js?t=1648439972749:11:5
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadConfigFromFile (/home/x80486/webapp/node_modules/vite/dist/node/chunks/dep-9c153816.js:71326:31)
    at async resolveConfig (/home/x80486/webapp/node_modules/vite/dist/node/chunks/dep-9c153816.js:70873:28)
    at async doBuild (/home/x80486/webapp/node_modules/vite/dist/node/chunks/dep-9c153816.js:38971:20)
    at async build (/home/x80486/webapp/node_modules/vite/dist/node/chunks/dep-9c153816.js:38959:16)
    at async CAC.<anonymous> (/home/x80486/webapp/node_modules/vite/dist/node/cli.js:738:9)
```

I'm using the latest versions of `Vite` and the plugin:

```json
{
  "private": true,
  "type": "module",
  "scripts": {
    "build": "vite build",
    "preview": "vite preview",
    "start": "vite dev"
  },
  "devDependencies": {
    "@types/node": "17.0.23",
    "vite": "2.8.6",
    "vite-plugin-nunjucks": "0.1.10"
  },
  "dependencies": {
    "jquery": "3.6.0"
  },
  "engines": {
    "node": "16.x"
  }
}
```

**Comment by x80486** [comment]
Removing `"type": "module"` is the issue here, though at this point all the `Vite` plugins should work with ESM, right?

**Comment by Jax-p** [comment]
That seems more like a [Vite](https://github.com/vitejs/vite) thing, but I'm glad you've solved it.
